"""add position column to employee

Revision ID: 15dc53774647
Revises: ec1cef7d1dd9
Create Date: 2025-08-29 23:30:04.778505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15dc53774647'
down_revision: Union[str, None] = 'ec1cef7d1dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('position', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('status', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('checkin', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('checkout', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('hire_date', sa.DateTime(), nullable=True))
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'checkout')
    op.drop_column('employees', 'checkin')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'position')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    # ### end Alembic commands ###
