"""made change

Revision ID: 2e5ebd5dc500
Revises: 15dc53774647
Create Date: 2025-08-29 23:55:15.883414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5ebd5dc500'
down_revision: Union[str, None] = '15dc53774647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with a temporary default to avoid NOT NULL violation
    op.add_column('employees', sa.Column('first_name', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('employees', sa.Column('last_name', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('employees', sa.Column('position', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('status', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('checkin', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('checkout', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('hire_date', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    
    # Remove old columns
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'name')
    
    # Remove the temporary server default
    op.alter_column('employees', 'first_name', server_default=None)
    op.alter_column('employees', 'last_name', server_default=None)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'checkout')
    op.drop_column('employees', 'checkin')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'position')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    # ### end Alembic commands ###
