"""renamed password to password_hash

Revision ID: 40c1a2e5de10
Revises: 832cabf7eda0
Create Date: 2025-08-27 19:31:36.133657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c1a2e5de10'
down_revision: Union[str, None] = '832cabf7eda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###
