"""init

Revision ID: 66392214012c
Revises: 19459b80ea17
Create Date: 2025-08-29 20:14:56.069185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66392214012c'
down_revision: Union[str, None] = '19459b80ea17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('salary', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'salary')
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###
