"""add password column

Revision ID: b1c549802c46
Revises: 40c1a2e5de10
Create Date: 2025-08-27 21:12:04.304344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c549802c46'
down_revision: Union[str, None] = '40c1a2e5de10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###
